#!/usr/bin/env bash
#
# DO NOT EDIT THIS FILE!
#
# If you need to run additional setup steps before the package tests,
# edit the run script in .travis.yml instead
#
# If you have any questions about this script, or think it is not general
# enough to cover your use case (i.e., you feel that you need to modify it
# anyway), please contact Max Horn <max.horn@math.uni-giessen.de>.
#
set -ex

# set up a custom GAP root containing only this package, so that
# we can force GAP to load the correct version of this package
mkdir -p gaproot/pkg/
ln -f -s $PWD gaproot/pkg/

# start GAP with custom GAP root, to ensure correct package version is loaded
GAP="$GAPROOT/bin/gap.sh -l $PWD/gaproot; --quitonbreak"

# Unless explicitly turned off by setting the NO_COVERAGE environment variable,
# we collect coverage data
if [[ -z $NO_COVERAGE ]]; then
    mkdir -p ${COVDIR-coverage}
    GAP="$GAP --cover ${COVDIR-coverage}/$(mktemp XXXXXX).coverage"
fi

# TODO: honor TestFile from PackageInfo record, but make sure that it
# is for the package in the current directory
$GAP ${GAP_TESTFILE:-tst/testall.g}
